sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ddutjnrevenge93/react-test -f ./client/Dockerfile.dev ./client 

script:
  - docker run -e CI=true ddutjnrevenge93/react-test npm test

after_success:
  - docker build -t complex-client ./client
  - docker build -t complex-nginx ./nginx
  - docker build -t complex-server ./server
  - docker build -t complex-worker ./worker
  # Tag the images with the correct repository names
  - docker tag complex-client ddutjnrevenge93/multi-client
  - docker tag complex-nginx ddutjnrevenge93/multi-nginx
  - docker tag complex-server ddutjnrevenge93/multi-server
  - docker tag complex-worker ddutjnrevenge93/multi-worker
  # Log in to the docker CLI (docker login)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push ddutjnrevenge93/multi-client
  - docker push ddutjnrevenge93/multi-nginx
  - docker push ddutjnrevenge93/multi-server
  - docker push ddutjnrevenge93/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-891377227663"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY